### ISSUE TITLE
Warum gibt es noch keine Testversion auf GitHub?

### ISSUE THREAD

**Issue by mrentsch65** [H4CK3R-01/TINF20C_ModellingWizard_Devices#11]
Habe leider nichts zum testen gefunden...

**Comment by H4CK3R-01** [comment]
Die Releases vom ausführbaren Programm finden sich aktuell, wie es sich für Github gehört, unter https://github.com/H4CK3R-01/TINF20C_ModellingWizard_Devices/releases.

Die aktuellste Version wäre also zur Zeit [v0.2](https://github.com/H4CK3R-01/TINF20C_ModellingWizard_Devices/releases/v0.2)
