### ISSUE TITLE
Umbenennung

### ISSUE THREAD

**Issue by NormalParameter** [H4CK3R-01/TINF20C_ModellingWizard_Devices#12]
Sollen wir vielleicht das Program noch englisch benennen ? Ich finde es komisch wenn unten Interfaces und Attachments sind und das Ding aber ... für Gerätemodelle heißt

![image](https://user-images.githubusercontent.com/76038781/165838664-e90cd108-618c-4d2c-a988-6e2632066f45.png)

**Comment by mhorst00** [comment]
This is known conflict as the name was chosen by the customer and should not be changed.
