### ISSUE TITLE
Welchen Sinn hat dieses Header-Tab und die dahinterliegenden Elemente?

### ISSUE THREAD

**Issue by mrentsch65** [H4CK3R-01/TINF20C_ModellingWizard_Devices#26]
![image](https://user-images.githubusercontent.com/50681355/167220383-4c90e0b2-89ad-467e-8441-b3762e6e6920.png)
Das sollte besser weggelassen werden!

**Comment by FlorianKellermann** [comment]
Guten Tag Herr Rentschler,

der Header-Tab war so ebenfalls bereits im Plugin zu finden:

![image](https://user-images.githubusercontent.com/72264222/167244188-eb8436f3-deda-4cf4-b64f-fcd8d67da2c8.png)

Wir empfinden, dass der Header-Tab einen guten ersten Eindruck über das importierte Modul liefert und somit für die usability hilfreich ist. Der Tab ist standardmäßig nicht geöffnet und wenn einen diese Informationen nicht interessieren, so wird man diese nie zu Gesicht bekommen. Daher haben wir ihn beibehalten.

Viele Grüße,
Florian Kellermann

**Comment by mrentsch65** [comment]
Bitte entfernen Sie den Tab, er verschlechtert nur die Usability der Bedienoberfläche (weniger ist mehr). Ausserdem funktioniert er nicht m.E. sowieso nicht richtig.

**Comment by H4CK3R-01** [comment]
Removed in Beta 5 (https://github.com/H4CK3R-01/TINF20C_ModellingWizard_Devices/releases/tag/v0.5)
