### ISSUE TITLE
Version with Known Issues corrected?

### ISSUE THREAD

**Issue by mrentsch65** [H4CK3R-01/TINF20C_ModellingWizard_Devices#29]
Hallo,

wird es bis Morgen noch eine v0.6 geben, wo die schlimmsten bekannten Bugs behoben sind?

**Comment by H4CK3R-01** [comment]
Ein Teil der Probleme wurde in Release [v0.5](https://github.com/H4CK3R-01/TINF20C_ModellingWizard_Devices/releases/tag/v0.5) behoben.
