### ISSUE TITLE
SRS: GUI-Entwurf fehlt vollständig

### ISSUE THREAD

**Issue by mrentsch65** [H4CK3R-01/TINF20C_ModellingWizard_Devices#5]
Der Entwurf einer verbesserten GUI & Usability für die neue Standalone-Anwendung ist zentrale Projektanforderung. Im SRS ist weder eine Usability-Analyse noch ein GUI-Entwurf zu finden! Bitte asap nachziehen!

**Comment by NormalParameter** [comment]
Hallo Herr Rentschler,

Im Repository finden Sie bereits seit der letzten Woche einen GUI-Entwurf.
Dieser wird inklusive Usability Konzept bald im SRS zu finden sein.
