### ISSUE TITLE
Wiki ist ungepflegt

### ISSUE THREAD

**Issue by mrentsch65** [H4CK3R-01/TINF20C_ModellingWizard_Devices#6]
Es wurde offensichtlich das Vorgängerprojekt geclont und die Inhalte teilweise unverändert belassen, z.B. das Kapitel "User Manual", welches inhaltlich so keinen Sinn mehr macht. Bitte bereinigen! 
Tip: Mittels Erstellung des Usermanuals gleich am Anfang im Rahmen der Anforderungsanalyse (SRS) könnte übrigens sehr gut das GUI-Design und die Usability des neuen Tools hergeleitet werden!

**Comment by Rripped** [comment]
Der alte User Manual wurde entfernt
