### ISSUE TITLE
Add sample files

### ISSUE THREAD

**Issue by H4CK3R-01** [H4CK3R-01/TINF20C_ModellingWizard_Devices#8]
Für die Entwicklung und das anschließende Testen werden Beispiel-Dateien benötigt, die von der Anwendung geöffnet werden sollen.
Speziell bräuchten wir AML-Dateien im CAEX 2.15 sowie im CAEX 3.0 Format.
 
Wir haben bereits die Datei http://wwwlehre.dhbw-stuttgart.de/~rentschler/Publications/IndustrialSensorLibrary_CAEX3_v1_1_0.aml, die sich aber nicht in dem Plugin aus dem letzten Jahr (https://github.com/DekaAthlos/TINF19C-ModellingWizard) öffnen lässt.

@mrentsch65, es wäre gut, wenn Sie uns die Dateien in den nächsten Tagen zukommen lassen könnten.

**Comment by H4CK3R-01** [comment]
Zusätzlich dazu benötigen wir IODD und GSD Dateien, um auch die Import-Funktionen zu Testen.

@mrentsch65

**Comment by mrentsch65** [comment]
Eine IODD finden Sie bspw. hier: 
https://shop.murrelektronik.de/I-O-Systeme/IO-Link-Devices/IO-Link-Hub/MVP12-Kunststoff-DI16-IOL-59401.html?listtype=search&searchparam=IO-Link%20Devices&src=search&srchPage=1&perPage=10&pos=1#

Eine GSD hier:
https://shop.murrelektronik.de/Elektronik-im-Schaltschrank/Switches/TREE-PROFINET-managed-Switch-5x10-100BT-IP67-Kunst-M12-58184.html?listtype=search&searchparam=TREE%20PROFINET%20managed%20Switch%20%205x10%2F100BT%20IP67%20%20Kunst.%20M12&src=search&srchPage=1&perPage=10&pos=1#

**Comment by mrentsch65** [comment]
Hier finden sich AMLX-Dateien:
![image](https://user-images.githubusercontent.com/50681355/160210749-d913b903-8aa0-4f4e-8f77-34aab2e29987.png)

**Comment by H4CK3R-01** [comment]
Vielen Dank für die Dateien :+1:
